DEMOCRAT_GOVERNORS = [
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Hawaii",
  "Illinois",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Michigan",
  "Minnesota",
  "Montana",
  "Nevada",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "Virginia",
  "Washington",
  "Wisconsin"
]

REPUBLICAN_GOVERNORS = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "Florida",
  "Georgia",
  "Idaho",
  "Indiana",
  "Iowa",
  "Maryland",
  "Massachusetts",
  "Mississippi",
  "Missouri",
  "Nebraska",
  "New Hampshire",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "West Virginia",
  "Wyoming"
]
